import mongoose from 'mongoose';

const BidSchema = new mongoose.Schema({
    id: { type: String, required: true, unique: true },
    customerName: String,
    projectName: String,
    deadline: String,
    receivedDate: String,
    status: String,
    currentStage: String,
    riskLevel: { type: String, default: 'Low' },
    estimatedValue: { type: Number, default: 0 },
    currency: { type: String, default: 'PKR' },
    bidSecurity: { type: String, default: '' },
    requiredSolutions: [String],
    summaryRequirements: String,
    scopeOfWork: String,
    qualificationCriteria: String,
    aiQualificationSummary: String,
    technicalQualificationChecklist: [mongoose.Schema.Types.Mixed],
    complianceChecklist: [mongoose.Schema.Types.Mixed],
    technicalDocuments: [mongoose.Schema.Types.Mixed],
    vendorQuotations: [mongoose.Schema.Types.Mixed],
    financialFormats: [mongoose.Schema.Types.Mixed],
    proposalSections: [mongoose.Schema.Types.Mixed],
    noBidReason: String,
    noBidReasonCategory: String,
    noBidComments: String,
    competitionPricing: String,
    keyLearnings: String,
    noBidStage: String,
    daysInStages: mongoose.Schema.Types.Map,
    stageHistory: [mongoose.Schema.Types.Mixed],
    submissionDate: String,
    aiQualificationScore: Number,
    jbcName: String,
    channel: String,
    region: String,
    contractDuration: String,
    customerPaymentTerms: String,
    vendorPaymentTerms: String,
    tcvExclTax: Number,
    tcvInclTax: Number,
    managementApprovalStatus: String,
    pricingApprovalStatus: String,
    approvingAuthorityRole: String,
    approvingAuthority: String,
    approvalRequestedDate: String,
    managementApprovalDate: String,
    identifiedRisks: [mongoose.Schema.Types.Mixed],
    mitigationPlan: [String],
    strategicRiskAssessment: mongoose.Schema.Types.Mixed,
    solutioningAIAnalysis: String,
    finalRiskAssessment: mongoose.Schema.Types.Mixed,
    aiQualificationAssessment: String,
    qualifyingFactors: [String],
    disqualifyingFactors: [String],
    aiConfidenceScore: Number,
    publishDate: String,
    complexity: String,
    preBidMeeting: mongoose.Schema.Types.Mixed,
    deliverablesSummary: [mongoose.Schema.Types.Mixed],
    integrityScoreBreakdown: mongoose.Schema.Types.Mixed,
    phaseTargets: mongoose.Schema.Types.Map,
}, { timestamps: true });

// Add indexes for performance
BidSchema.index({ status: 1, deadline: 1 }); // Compound index for filtering
BidSchema.index({ customerName: 1 });
BidSchema.index({ receivedDate: -1 });
BidSchema.index({ 'stageHistory.timestamp': -1 });
BidSchema.index({ jbcName: 1, status: 1 });
BidSchema.index({ estimatedValue: -1 });

export const Bid = mongoose.model('Bid', BidSchema);
