import mongoose from 'mongoose';

const BidSchema = new mongoose.Schema({
    id: { type: String, required: true, unique: true },
    customerName: { type: String, required: true },
    projectName: { type: String, required: true },
    deadline: { type: String, required: true },
    receivedDate: { type: String, required: true },
    status: { type: String, required: true },
    currentStage: { type: String, required: true },
    riskLevel: { type: String, required: true },
    estimatedValue: { type: Number, required: true },
    currency: { type: String, required: true },
    bidSecurity: { type: String, required: true },
    requiredSolutions: [String],
    summaryRequirements: String,
    scopeOfWork: String,
    qualificationCriteria: String,
    aiQualificationSummary: String,
    technicalQualificationChecklist: [mongoose.Schema.Types.Mixed],
    complianceChecklist: [mongoose.Schema.Types.Mixed],
    technicalDocuments: [mongoose.Schema.Types.Mixed],
    vendorQuotations: [mongoose.Schema.Types.Mixed],
    financialFormats: [mongoose.Schema.Types.Mixed],
    proposalSections: [mongoose.Schema.Types.Mixed],
    noBidReason: String,
    noBidReasonCategory: String,
    noBidComments: String,
    competitionPricing: String,
    keyLearnings: String,
    noBidStage: String,
    daysInStages: mongoose.Schema.Types.Map,
    stageHistory: [mongoose.Schema.Types.Mixed],
    submissionDate: String,
    aiQualificationScore: Number,
    jbcName: String,
    channel: String,
    region: String,
    contractDuration: String,
    customerPaymentTerms: String,
    vendorPaymentTerms: String,
    tcvExclTax: Number,
    tcvInclTax: Number,
    managementApprovalStatus: String,
    pricingApprovalStatus: String,
    approvingAuthorityRole: String,
    approvingAuthority: String,
    approvalRequestedDate: String,
    managementApprovalDate: String,
    identifiedRisks: [mongoose.Schema.Types.Mixed],
    mitigationPlan: [String],
    strategicRiskAssessment: mongoose.Schema.Types.Mixed,
    solutioningAIAnalysis: String,
    finalRiskAssessment: mongoose.Schema.Types.Mixed,
    aiQualificationAssessment: String,
    qualifyingFactors: [String],
    disqualifyingFactors: [String],
    aiConfidenceScore: Number,
    publishDate: String,
    complexity: String,
    preBidMeeting: mongoose.Schema.Types.Mixed,
    deliverablesSummary: [mongoose.Schema.Types.Mixed],
    integrityScoreBreakdown: mongoose.Schema.Types.Mixed,
}, { timestamps: true });

export const Bid = mongoose.model('Bid', BidSchema);
